name: Terraform Chouse Action

on:
  workflow_dispatch:
    inputs:
      command:
        type: choice
        description: Select Terraform command to execute
        default: plan
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
      TF_COMMAND: ${{ github.event.inputs.command }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Command
      run: |
        echo "Executing Terraform $TF_COMMAND"
        case $TF_COMMAND in
          plan)
            terraform plan
            ;;
          apply)
            terraform apply -auto-approve
            ;;
          destroy)
            terraform destroy -auto-approve
            ;;
          *)
            echo "No valid command selected."
            ;;
        esac
